version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/docker
      - public-data:/docker/public
      - tmp-data:/docker/tmp
      - log-data:/docker/log
    depends_on:
      - db

  web:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/docker.conf
      - public-data:/docker/public
      - tmp-data:/docker/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
    